name: Terraform Workflow
on:
  workflow_call:
    inputs:
      account:
        required: true
        type: string
    secrets:
      AWS_ROOT_ACCOUNT:
        required: true
      BEDROCK_TF_VARS: # Ensure these are base64 encoded in secrets, we need linefeeds
        required: true
      BEDROCK_TF_STATE: # Ensure these are base64 encoded in secrets, we need linefeeds
        required: true

jobs:
  authentication:
    name: Terraform
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        working-directory: ./tf/${{ inputs.account }}
    env:
      account: ${{ inputs.account }}
      AWS_ROOT_ACCOUNT: ${{ secrets.AWS_ROOT_ACCOUNT }}
      BEDROCK_TF_VARS: ${{ secrets.BEDROCK_TF_VARS }}
      BEDROCK_TF_STATE: ${{ secrets.BEDROCK_TF_STATE }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

# Github Actions method that replaces the aws_assumerole_oidc.sh deploy script
      - name: AWS credentials Bootstrap (GitHub Action)
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ROOT_ACCOUNT }}:role/Github-Bootstrap
          role-session-name: GitHub-bootstrap
          aws-region: ap-southeast-2

      - name: Export Session Credentials
        id: bootstrap
        run: |
          if [ ! -f terraform.tfvars ]; then echo '${{ env.BEDROCK_TF_VARS }}' | base64 --decode > "terraform.tfvars"; else echo "tfvars part of repo"; fi
          RGN="$(cat terraform.tfvars | grep base_region | cut -d = -f2 | tr -d '[:blank:]\"')"

          echo "::set-output name=STS_RGN::$RGN"
          echo "::set-output name=STS_ID::$AWS_ACCESS_KEY_ID"
          echo "::set-output name=STS_KEY::$AWS_SECRET_ACCESS_KEY"
          echo "::set-output name=STS_TKN::$AWS_SESSION_TOKEN"

      - name: AWS credentials Admin
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ steps.bootstrap.outputs.STS_ID }} 
          aws-secret-access-key: ${{ steps.bootstrap.outputs.STS_KEY }}
          aws-session-token: ${{ steps.bootstrap.outputs.STS_TKN }}
          aws-region: ${{ steps.bootstrap.outputs.STS_RGN }}
          role-to-assume: arn:aws:iam::${{ env.AWS_ROOT_ACCOUNT }}:role/bedrock-deploy
          role-skip-session-tagging: true
          role-duration-seconds: 3600
          role-session-name: MgmtAdminSession

      - name: Terraform State and Init
        env:
          ENVIRONMENT: ${{ env.account }}
        run: |
          ../deploy/tf_state.sh

      - name: Terraform Import (Org Account Only)
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && env.account == 'org'
        run: ../deploy/tf_import.sh

      - name: Terraform Plan
        run: ../deploy/tf_plan.sh

      - name: Terraform Apply
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        run: ../deploy/tf_deploy.sh
